resolver: lts-7.14

packages:
- '.'

extra-deps:
- rawstring-qm-0.2.3.0
- data-lens-2.11.1

flags: {}
extra-package-dbs: []
allow-newer: true
compiler: ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghc:
    linux64:
      8.0.2:
        url: https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-deb8-linux.tar.xz
        content-length: 114373576
        sha1: f298b7d0f37cc9ded7ac66b2662b0fa5ac6d0809
    macosx:
      8.0.2:
        url: https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-apple-darwin.tar.xz
        content-length: 113945284
        sha1: 5bfd2cef149bd2936cc56bb4b526cbc56a0e7f28
    windows64:
      8.0.2:
        url: https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-unknown-mingw32.tar.xz
        content-length: 156817208
        sha1: 18d8eadb52e86583c14019be53910e02dbe84f1d
