packages:
- '.'
- '..'
- '../../shakespeare'
- location:
    git: https://github.com/yesodweb/yesod
    commit: 6d03e6beedf6d6adccace2adeffad1a09b1a46eb
  subdirs:
  - yesod-bin
  extra-dep: true

extra-deps:
- rawstring-qm-0.2.3.0
- data-lens-2.11.1
- typed-process-0.1.0.0
- containers-0.5.9.1
#- base-4.9.1.0
#- unix-2.7.2.1

flags: {}
extra-package-dbs: []

#compiler: ghc-8.0.2
#compiler-check: match-exact

resolver: lts-7.16

